<?php

namespace AppBundle\Repository;

/**
 * db_studentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class db_studentsRepository extends \Doctrine\ORM\EntityRepository
{
}
